### ISSUE TITLE
Images not displayed when using watermark

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#423]
When using watermarks, no images are displayed. 

Error message:

[04-Feb-2015 19:10:59 Europe/Paris] PHP Warning:  set_error_handler() expects the argument (imagettftextErrorHandler) to be a valid callback in C:\wamp\www\webtrees\mediafirewall.php on line 190

[04-Feb-2015 19:10:59 Europe/Paris] PHP Stack trace:

[04-Feb-2015 19:10:59 Europe/Paris] PHP   1. {main}() C:\wamp\www\webtrees\mediafirewall.php:0

[04-Feb-2015 19:10:59 Europe/Paris] PHP   2. Webtrees\applyWatermark() C:\wamp\www\webtrees\mediafirewall.php:391

[04-Feb-2015 19:10:59 Europe/Paris] PHP   3. Webtrees\embedText() C:\wamp\www\webtrees\mediafirewall.php:87

[04-Feb-2015 19:10:59 Europe/Paris] PHP   4. set_error_handler() C:\wamp\www\webtrees\mediafirewall.php:190

[04-Feb-2015 19:10:59 Europe/Paris] PHP Warning:  set_error_handler() expects the argument (imagettftextErrorHandler) to be a valid callback in C:\wamp\www\webtrees\mediafirewall.php on line 190

[04-Feb-2015 19:10:59 Europe/Paris] PHP Stack trace:

[04-Feb-2015 19:10:59 Europe/Paris] PHP   1. {main}() C:\wamp\www\webtrees\mediafirewall.php:0

[04-Feb-2015 19:10:59 Europe/Paris] PHP   2. Webtrees\applyWatermark() C:\wamp\www\webtrees\mediafirewall.php:391

[04-Feb-2015 19:10:59 Europe/Paris] PHP   3. Webtrees\embedText() C:\wamp\www\webtrees\mediafirewall.php:88

[04-Feb-2015 19:10:59 Europe/Paris] PHP   4. set_error_handler() C:\wamp\www\webtrees\mediafirewall.php:190

**Comment by fisharebest** [comment]
fixed

**Comment by HRN-webtrees** [comment]
Highlighted images still not visible

**Comment by fisharebest** [comment]
> Highlighted images still not visible

Can you be more specific, as I can see images everywhere I expect....

**Comment by HRN-webtrees** [comment]
Checking further, this seems to be related to the Favorites block.
For indi's added to to this block, the thumbnail for highlighted image is not displayed on the INDI page, nor in the Album/Media tabs. Though, clicking the broken thumb will open the image.

Settings:
Add watermarks to thumbnails? Yes
Images without watermarks - Show to members

**Comment by HRN-webtrees** [comment]
Further testing:

When deleting an individual from the Favorites block, the problem remains. No thumbnail displayed.
When adding new individuals to the Favorites block, there is no problem. Thumbnails are displayed.

So this seems to affect only individuals already listed in the Favorites block
